[package]
name = "nexa-lsp"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "nexa-lsp"
path = "src/main.rs"

[dependencies]
nexa-diagnostics = { path = "../nexa-diagnostics" }
nexa-syntax = { path = "../nexa-syntax" }
nexa-compiler = { path = "../nexa-compiler" }
nexa-ir = { path = "../nexa-ir" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
